-- apply changes
create table instance (
  id                            bigint generated by default as identity not null,
  "key"                         character varying not null,
  location                      character varying,
  release_version               character varying,
  release_number                character varying,
  status                        character varying,
  environment                   integer not null,
  constraint ck_instance_environment check ( environment in (1,2)),
  constraint uq_instance_key unique ("key"),
  constraint pk_instance primary key (id)
);

create table subscription (
  id                            bigint generated by default as identity not null,
  instance_id                   bigint,
  user_id                       bigint,
  constraint pk_subscription primary key (id)
);

create table users (
  id                            bigint generated by default as identity not null,
  username                      character varying not null,
  constraint uq_users_username unique (username),
  constraint pk_users primary key (id)
);

-- foreign keys and indices
create index ix_subscription_instance_id on subscription (instance_id);
alter table subscription add constraint fk_subscription_instance_id foreign key (instance_id) references instance (id) on delete restrict on update restrict;

create index ix_subscription_user_id on subscription (user_id);
alter table subscription add constraint fk_subscription_user_id foreign key (user_id) references users (id) on delete restrict on update restrict;

