-- apply changes
create table instance (
  id                            bigint generated by default as identity not null,
  key                           varchar(255) not null,
  location                      varchar(255),
  release_version               varchar(255),
  release_number                varchar(255),
  status                        varchar(255),
  environment                   varchar(10),
  constraint ck_instance_environment check ( environment in ('SANDBOX','PRODUCTION')),
  constraint uq_instance_key unique (key),
  constraint pk_instance primary key (id)
);

create table instance_subscriber (
  id                            bigint generated by default as identity not null,
  instance_id                   bigint not null,
  subscriber_id                 bigint not null,
  constraint pk_instance_subscriber primary key (id)
);

create table subscriber (
  id                            bigint generated by default as identity not null,
  username                      varchar(255) not null,
  constraint uq_subscriber_username unique (username),
  constraint pk_subscriber primary key (id)
);

create index ix_instance_subscriber_instance_id on instance_subscriber (instance_id);
alter table instance_subscriber add constraint fk_instance_subscriber_instance_id foreign key (instance_id) references instance (id) on delete restrict on update restrict;

create index ix_instance_subscriber_subscriber_id on instance_subscriber (subscriber_id);
alter table instance_subscriber add constraint fk_instance_subscriber_subscriber_id foreign key (subscriber_id) references subscriber (id) on delete restrict on update restrict;

